### ISSUE TITLE
Add active class to global nav via JS

### ISSUE THREAD

**Issue by christinatruong** [WomenAndTech/style_guide#7]
Add "active" style to corresponding nav item representing the current page.

**Comment by christinatruong** [comment]
How this is created may depend on how the pages are loaded. @raykao, when new pages are created, will they be full pages (with global header & footer) that refresh on page load or will just the middle content area be reloaded & updated on the page?

**Comment by raykao** [comment]
Middle content area will be inserted into the page.  Ember uses the browser location history to know where it's at (also known as state or path in some literature).  As a result it will know when to add the active class to a link(s) if we're using what are know as link helpers in the pages...which we are :)

**Comment by christinatruong** [comment]
We're using PHP includes for the static site so I'll make it work for that. We can revisit this when we have the editor option.  Will close this issue for now.
